### ISSUE TITLE
Create a card template for startup directory

### ISSUE THREAD

**Issue by coastaldemigod** [EDC-BITM/EDC-BITM#2]
The card should have the following features -
1. Name of the entrepreneur 
2. Batch and branch of the entrepreneur
3. Photograph of the entrepreneur 
4. Link to social profiles of the entrepreneur ( Linkedin )
4. Name of the startup ( anchored to it's working link )
5. Location of the startup

Add any more feature if you feel it can be of use.

For theme and colours refer to the cards in team.html
Maintain a simillar theme.

**Comment by Kajal-krn** [comment]
I will be doing this part.

**Comment by coastaldemigod** [comment]
I have added you as a maintainer.
All the work will be done on "dev" branch [ Use ( git checkout -b dev ) to to come to this branch ]
Try to come finish the work by tuesday.

**Comment by Kajal-krn** [comment]
Cards designed and sent internally.

**Comment by coastaldemigod** [comment]
Good Work. We'll review the code and commit them soon.

**Comment by Kajal-krn** [comment]
Okay.. Thank you for the chance.
